[package]
name = "lox_interpreter"
version = "0.1.0"
authors = ["Joshua Rakita <joshuarakita@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rstest = "0.10.0"
