name: Pull Request

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build @ joraki
      run: cargo build --verbose
      working-directory: "./rakitaj/lox_interpreter"
    - name: Test @ joraki
      run: cargo test --verbose
      working-directory: "./rakitaj/lox_interpreter"
    - name: Build @ benbp
      run: cargo build --verbose
      working-directory: "./benbp/rust/interpreter"
    - name: Test @ benbp
      run: cargo test --verbose
      working-directory: "./benbp/rust/interpreter"

